baseURL = "https://ot-gorozan.blagorussia.ru/"
languageCode = "ru-ru"
title = "Конкурс От благодарных горожан"

[params]
  description = "Конкурс От благодарных горожан"
  author = "НП «Общественное благополучие Воронежа»"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
