baseURL = "https://ot-gorozan.blagorussia.ru/"
languageCode = "ru-ru"
title = "Конкурс От благодарных горожан"

[params]
  description = "Если человек сделал благое дело, то его надо поддержать в этом. Поддержать для того, что бы он знал, что его начинания одобряют и другие люди!"
  author = "НП «Общественное благополучие Воронежа»"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
